
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


    initialSize: 1
    minIdle: 3
    maxActive: 20

    maxWait: 60000

    timeBetweenEvictionRunsMillis: 60000

    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    filters: stat,wall,slf4j

    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    useGlobalDataSourceStat: true


mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

logging:
  file: ./text.log




